init:
  - git config --global core.autocrlf true
build_script:
  - ps: .\build.ps1 /p:TestGroup=SqlServer
clone_depth: 1
test: off
deploy: off
# See http://www.appveyor.com/docs/services-databases
services:
  - mssql2016
branches:
  only:
    - master
    - release
    - dev
    - /^(.*\/)?ci-.*$/
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    Test__SqlServer__DefaultConnection: Server=(local)\SQL2016;Database=master;User ID=sa;Password=Password12!
matrix:
  fast_finish: true
artifacts:
  - path: 'artifacts\build\*.nupkg'
os: Visual Studio 2017
