name: Test Cosmos

on:
  pull_request:
    branches:
      - main
      - feature/*
      - release/*

permissions: {}

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Start Cosmos Emulator
        run: |
          Import-Module "$env:ProgramFiles\Azure Cosmos DB Emulator\PSModules\Microsoft.Azure.CosmosDB.Emulator"
          Start-CosmosDbEmulator -Timeout 540 -NoUI -NoTelemetry -NoFirewall -EnablePreview

      - name: Checkout
        uses: actions/checkout@v5
        
      - name: Build
        run: build.cmd -test /p:Projects=${{ github.workspace }}\test\EFCore.Cosmos.FunctionalTests\EFCore.Cosmos.FunctionalTests.csproj
        shell: cmd
        env:
           Test__Cosmos__SkipConnectionCheck: true

      - name: Publish Test Results
        uses: actions/upload-artifact@v5
        if: always()
        with:
          name: test-results
          path: artifacts/log/Debug/*
